<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net9.0;net10.0</TargetFrameworks>
    <TargetFrameworks
      Condition="'$(NETCoreSdkVersion)' != '' and $([MSBuild]::VersionLessThan('$(NETCoreSdkVersion)', '10.0.100'))"
      >net9.0</TargetFrameworks>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsAotCompatible>true</IsAotCompatible>
    <Version>0.1.0-preview.1</Version>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <DotNativePluginEntry>InAppWebViewPlugin</DotNativePluginEntry>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference
      Include="../dotNative/src/DotNative/DotNative.csproj"
      Condition="Exists('../dotNative/src/DotNative/DotNative.csproj')"
    />
    <PackageReference
      Include="DotNative"
      Version="0.1.0-preview.10"
      Condition="!Exists('../dotNative/src/DotNative/DotNative.csproj')"
    />
    <None Remove="Platform/**/*;buildTransitive/**/*" />
    <None Include="Platform/**/*;buildTransitive/**/*" Pack="true" PackagePath="%(Identity)" />
    <None Remove="README.md" />
    <None Include="README.md" Pack="true" PackagePath="README.md" />
    <None Remove="LICENSE" />
    <None Include="LICENSE" Pack="true" PackagePath="LICENSE" />
  </ItemGroup>
  <ItemGroup>
    <None Remove="ORIGIN.md" />
    <None Include="ORIGIN.md" Pack="true" PackagePath="ORIGIN.md" />
  </ItemGroup>
  <Import Project="build/PluginAuthoring.props" />
  <Import Project="build/PluginAuthoring.targets" />
</Project>
